name: StudyRoomBooking
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Firebase Plugins
  firebase_core: 0.4.0+9
  firebase_analytics: 5.0.2
  firebase_auth: 0.14.0+5
  cloud_firestore: 0.12.9+5
  # iOS Icons
  cupertino_icons: 0.1.2
  # Bottom Bar with FAB
  bubble_bottom_bar: 1.2.0
  # Customizable Calendar
  table_calendar: 2.2.2
  # Locale formatting
  intl: 0.16.1
  # Barcode & QR Code scanning
  barcode_scan_fix: 1.0.2
  # Additional Material Design Icons
  material_design_icons_flutter: 2.7.94
  # Getting & Setting Key-Value Pairs in phone Storage
  shared_preferences: 0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/cat.png
  fonts:
    - family: Calibri
      fonts:
        - asset: fonts/Calibri-Light.ttf
        - asset: fonts/Calibri-Regular.ttf
        - asset: fonts/Calibri-Bold.TTF
          weight: 700
  uses-material-design: true
